#if !DISABLE_PLAYFABCLIENT_API
using System;
using PlayFab.ClientModels;
using PlayFab.Internal;
using UnityEngine;

namespace PlayFab
{
    /// <summary>
    /// APIs which provide the full range of PlayFab features available to the client - authentication, account and data management, inventory, friends, matchmaking, reporting, and platform-specific functionality
    /// </summary>
    public static class PlayFabClientAPI
    {

        /// <summary>
        /// Check to See if the client is logged in.
        /// </summary>
        /// <returns>boolean</returns>
        public static bool IsClientLoggedIn()
        {
            return PlayFabHttp.IsClientLoggedIn();
        }

        /// <summary>
        /// Gets a Photon custom authentication token that can be used to securely join the player into a Photon room. See https://api.playfab.com/docs/using-photon-with-playfab/ for more details.
        /// </summary>
        public static void GetPhotonAuthenticationToken(GetPhotonAuthenticationTokenRequest request, Action<GetPhotonAuthenticationTokenResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPhotonAuthenticationTokenRequest, GetPhotonAuthenticationTokenResult>("Client", "/Client/GetPhotonAuthenticationToken", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using the Android device identifier, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithAndroidDeviceID(LoginWithAndroidDeviceIDRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithAndroidDeviceIDRequest, LoginResult>("Client", "/Client/LoginWithAndroidDeviceID", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a custom unique identifier generated by the title, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithCustomID(LoginWithCustomIDRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithCustomIDRequest, LoginResult>("Client", "/Client/LoginWithCustomID", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user into the PlayFab account, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithEmailAddress(LoginWithEmailAddressRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithEmailAddressRequest, LoginResult>("Client", "/Client/LoginWithEmailAddress", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a Facebook access token, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithFacebook(LoginWithFacebookRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithFacebookRequest, LoginResult>("Client", "/Client/LoginWithFacebook", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using an iOS Game Center player identifier, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithGameCenter(LoginWithGameCenterRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithGameCenterRequest, LoginResult>("Client", "/Client/LoginWithGameCenter", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a Google account access token(https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil#public-methods), returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithGoogleAccount(LoginWithGoogleAccountRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithGoogleAccountRequest, LoginResult>("Client", "/Client/LoginWithGoogleAccount", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using the vendor-specific iOS device identifier, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithIOSDeviceID(LoginWithIOSDeviceIDRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithIOSDeviceIDRequest, LoginResult>("Client", "/Client/LoginWithIOSDeviceID", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a Kongregate player account.
        /// </summary>
        public static void LoginWithKongregate(LoginWithKongregateRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithKongregateRequest, LoginResult>("Client", "/Client/LoginWithKongregate", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user into the PlayFab account, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithPlayFab(LoginWithPlayFabRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithPlayFabRequest, LoginResult>("Client", "/Client/LoginWithPlayFab", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a Steam authentication ticket, returning a session identifier that can subsequently be used for API calls which require an authenticated user
        /// </summary>
        public static void LoginWithSteam(LoginWithSteamRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithSteamRequest, LoginResult>("Client", "/Client/LoginWithSteam", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Signs the user in using a Twitch access token.
        /// </summary>
        public static void LoginWithTwitch(LoginWithTwitchRequest request, Action<LoginResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<LoginWithTwitchRequest, LoginResult>("Client", "/Client/LoginWithTwitch", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Registers a new Playfab user account, returning a session identifier that can subsequently be used for API calls which require an authenticated user. You must supply either a username or an email address.
        /// </summary>
        public static void RegisterPlayFabUser(RegisterPlayFabUserRequest request, Action<RegisterPlayFabUserResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            request.TitleId = request.TitleId ?? PlayFabSettings.TitleId;
            if (request.TitleId == null) throw new Exception("Must be have PlayFabSettings.TitleId set to call this method");

            PlayFabHttp.MakeApiCall<RegisterPlayFabUserRequest, RegisterPlayFabUserResult>("Client", "/Client/RegisterPlayFabUser", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Adds playfab username/password auth to an existing semi-anonymous account created via a 3rd party auth method.
        /// </summary>
        public static void AddUsernamePassword(AddUsernamePasswordRequest request, Action<AddUsernamePasswordResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AddUsernamePasswordRequest, AddUsernamePasswordResult>("Client", "/Client/AddUsernamePassword", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the user's PlayFab account details
        /// </summary>
        public static void GetAccountInfo(GetAccountInfoRequest request, Action<GetAccountInfoResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetAccountInfoRequest, GetAccountInfoResult>("Client", "/Client/GetAccountInfo", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves all of the user's different kinds of info.
        /// </summary>
        public static void GetPlayerCombinedInfo(GetPlayerCombinedInfoRequest request, Action<GetPlayerCombinedInfoResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayerCombinedInfoRequest, GetPlayerCombinedInfoResult>("Client", "/Client/GetPlayerCombinedInfo", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Facebook identifiers.
        /// </summary>
        public static void GetPlayFabIDsFromFacebookIDs(GetPlayFabIDsFromFacebookIDsRequest request, Action<GetPlayFabIDsFromFacebookIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromFacebookIDsRequest, GetPlayFabIDsFromFacebookIDsResult>("Client", "/Client/GetPlayFabIDsFromFacebookIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Game Center identifiers (referenced in the Game Center Programming Guide as the Player Identifier).
        /// </summary>
        public static void GetPlayFabIDsFromGameCenterIDs(GetPlayFabIDsFromGameCenterIDsRequest request, Action<GetPlayFabIDsFromGameCenterIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromGameCenterIDsRequest, GetPlayFabIDsFromGameCenterIDsResult>("Client", "/Client/GetPlayFabIDsFromGameCenterIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Google identifiers. The Google identifiers are the IDs for the user accounts, available as "id" in the Google+ People API calls.
        /// </summary>
        public static void GetPlayFabIDsFromGoogleIDs(GetPlayFabIDsFromGoogleIDsRequest request, Action<GetPlayFabIDsFromGoogleIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromGoogleIDsRequest, GetPlayFabIDsFromGoogleIDsResult>("Client", "/Client/GetPlayFabIDsFromGoogleIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Kongregate identifiers. The Kongregate identifiers are the IDs for the user accounts, available as "user_id" from the Kongregate API methods(ex: http://developers.kongregate.com/docs/client/getUserId).
        /// </summary>
        public static void GetPlayFabIDsFromKongregateIDs(GetPlayFabIDsFromKongregateIDsRequest request, Action<GetPlayFabIDsFromKongregateIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromKongregateIDsRequest, GetPlayFabIDsFromKongregateIDsResult>("Client", "/Client/GetPlayFabIDsFromKongregateIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Steam identifiers. The Steam identifiers  are the profile IDs for the user accounts, available as SteamId in the Steamworks Community API calls.
        /// </summary>
        public static void GetPlayFabIDsFromSteamIDs(GetPlayFabIDsFromSteamIDsRequest request, Action<GetPlayFabIDsFromSteamIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromSteamIDsRequest, GetPlayFabIDsFromSteamIDsResult>("Client", "/Client/GetPlayFabIDsFromSteamIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the unique PlayFab identifiers for the given set of Twitch identifiers. The Twitch identifiers are the IDs for the user accounts, available as "_id" from the Twitch API methods (ex: https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser).
        /// </summary>
        public static void GetPlayFabIDsFromTwitchIDs(GetPlayFabIDsFromTwitchIDsRequest request, Action<GetPlayFabIDsFromTwitchIDsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayFabIDsFromTwitchIDsRequest, GetPlayFabIDsFromTwitchIDsResult>("Client", "/Client/GetPlayFabIDsFromTwitchIDs", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// NOTE: This call will be deprecated soon. For fetching the data for a given user  use GetPlayerCombinedInfo. For looking up users from the client api, we are in the process of adding a new api call. Once that call is ready, this one will be deprecated.  Retrieves all requested data for a user in one unified request. By default, this API returns all  data for the locally signed-in user. The input parameters may be used to limit the data retrieved to any subset of the available data, as well as retrieve the available data for a different user. Note that certain data, including inventory, virtual currency balances, and personally identifying information, may only be retrieved for the locally signed-in user. In the example below, a request is made for the account details, virtual currency balances, and specified user data for the locally signed-in user.
        /// </summary>
        public static void GetUserCombinedInfo(GetUserCombinedInfoRequest request, Action<GetUserCombinedInfoResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserCombinedInfoRequest, GetUserCombinedInfoResult>("Client", "/Client/GetUserCombinedInfo", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Android device identifier to the user's PlayFab account
        /// </summary>
        public static void LinkAndroidDeviceID(LinkAndroidDeviceIDRequest request, Action<LinkAndroidDeviceIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkAndroidDeviceIDRequest, LinkAndroidDeviceIDResult>("Client", "/Client/LinkAndroidDeviceID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the custom identifier, generated by the title, to the user's PlayFab account
        /// </summary>
        public static void LinkCustomID(LinkCustomIDRequest request, Action<LinkCustomIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkCustomIDRequest, LinkCustomIDResult>("Client", "/Client/LinkCustomID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Facebook account associated with the provided Facebook access token to the user's PlayFab account
        /// </summary>
        public static void LinkFacebookAccount(LinkFacebookAccountRequest request, Action<LinkFacebookAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkFacebookAccountRequest, LinkFacebookAccountResult>("Client", "/Client/LinkFacebookAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Game Center account associated with the provided Game Center ID to the user's PlayFab account
        /// </summary>
        public static void LinkGameCenterAccount(LinkGameCenterAccountRequest request, Action<LinkGameCenterAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkGameCenterAccountRequest, LinkGameCenterAccountResult>("Client", "/Client/LinkGameCenterAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the currently signed-in user account to the Google account specified by the Google account access token (https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil#public-methods).
        /// </summary>
        public static void LinkGoogleAccount(LinkGoogleAccountRequest request, Action<LinkGoogleAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkGoogleAccountRequest, LinkGoogleAccountResult>("Client", "/Client/LinkGoogleAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the vendor-specific iOS device identifier to the user's PlayFab account
        /// </summary>
        public static void LinkIOSDeviceID(LinkIOSDeviceIDRequest request, Action<LinkIOSDeviceIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkIOSDeviceIDRequest, LinkIOSDeviceIDResult>("Client", "/Client/LinkIOSDeviceID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Kongregate identifier to the user's PlayFab account
        /// </summary>
        public static void LinkKongregate(LinkKongregateAccountRequest request, Action<LinkKongregateAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkKongregateAccountRequest, LinkKongregateAccountResult>("Client", "/Client/LinkKongregate", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Steam account associated with the provided Steam authentication ticket to the user's PlayFab account
        /// </summary>
        public static void LinkSteamAccount(LinkSteamAccountRequest request, Action<LinkSteamAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkSteamAccountRequest, LinkSteamAccountResult>("Client", "/Client/LinkSteamAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Links the Twitch account associated with the token to the user's PlayFab account.
        /// </summary>
        public static void LinkTwitch(LinkTwitchAccountRequest request, Action<LinkTwitchAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LinkTwitchAccountRequest, LinkTwitchAccountResult>("Client", "/Client/LinkTwitch", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Submit a report for another player (due to bad bahavior, etc.), so that customer service representatives for the title can take action concerning potentially toxic players.
        /// </summary>
        public static void ReportPlayer(ReportPlayerClientRequest request, Action<ReportPlayerClientResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ReportPlayerClientRequest, ReportPlayerClientResult>("Client", "/Client/ReportPlayer", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Forces an email to be sent to the registered email address for the user's account, with a link allowing the user to change the password
        /// </summary>
        public static void SendAccountRecoveryEmail(SendAccountRecoveryEmailRequest request, Action<SendAccountRecoveryEmailResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            
            PlayFabHttp.MakeApiCall<SendAccountRecoveryEmailRequest, SendAccountRecoveryEmailResult>("Client", "/Client/SendAccountRecoveryEmail", request , null, resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Android device identifier from the user's PlayFab account
        /// </summary>
        public static void UnlinkAndroidDeviceID(UnlinkAndroidDeviceIDRequest request, Action<UnlinkAndroidDeviceIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkAndroidDeviceIDRequest, UnlinkAndroidDeviceIDResult>("Client", "/Client/UnlinkAndroidDeviceID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related custom identifier from the user's PlayFab account
        /// </summary>
        public static void UnlinkCustomID(UnlinkCustomIDRequest request, Action<UnlinkCustomIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkCustomIDRequest, UnlinkCustomIDResult>("Client", "/Client/UnlinkCustomID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Facebook account from the user's PlayFab account
        /// </summary>
        public static void UnlinkFacebookAccount(UnlinkFacebookAccountRequest request, Action<UnlinkFacebookAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkFacebookAccountRequest, UnlinkFacebookAccountResult>("Client", "/Client/UnlinkFacebookAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Game Center account from the user's PlayFab account
        /// </summary>
        public static void UnlinkGameCenterAccount(UnlinkGameCenterAccountRequest request, Action<UnlinkGameCenterAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkGameCenterAccountRequest, UnlinkGameCenterAccountResult>("Client", "/Client/UnlinkGameCenterAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Google account from the user's PlayFab account (https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil#public-methods).
        /// </summary>
        public static void UnlinkGoogleAccount(UnlinkGoogleAccountRequest request, Action<UnlinkGoogleAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkGoogleAccountRequest, UnlinkGoogleAccountResult>("Client", "/Client/UnlinkGoogleAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related iOS device identifier from the user's PlayFab account
        /// </summary>
        public static void UnlinkIOSDeviceID(UnlinkIOSDeviceIDRequest request, Action<UnlinkIOSDeviceIDResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkIOSDeviceIDRequest, UnlinkIOSDeviceIDResult>("Client", "/Client/UnlinkIOSDeviceID", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Kongregate identifier from the user's PlayFab account
        /// </summary>
        public static void UnlinkKongregate(UnlinkKongregateAccountRequest request, Action<UnlinkKongregateAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkKongregateAccountRequest, UnlinkKongregateAccountResult>("Client", "/Client/UnlinkKongregate", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Steam account from the user's PlayFab account
        /// </summary>
        public static void UnlinkSteamAccount(UnlinkSteamAccountRequest request, Action<UnlinkSteamAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkSteamAccountRequest, UnlinkSteamAccountResult>("Client", "/Client/UnlinkSteamAccount", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Unlinks the related Twitch account from the user's PlayFab account.
        /// </summary>
        public static void UnlinkTwitch(UnlinkTwitchAccountRequest request, Action<UnlinkTwitchAccountResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlinkTwitchAccountRequest, UnlinkTwitchAccountResult>("Client", "/Client/UnlinkTwitch", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Updates the title specific display name for the user
        /// </summary>
        public static void UpdateUserTitleDisplayName(UpdateUserTitleDisplayNameRequest request, Action<UpdateUserTitleDisplayNameResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateUserTitleDisplayNameRequest, UpdateUserTitleDisplayNameResult>("Client", "/Client/UpdateUserTitleDisplayName", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked friends of the current player for the given statistic, starting from the indicated point in the leaderboard
        /// </summary>
        public static void GetFriendLeaderboard(GetFriendLeaderboardRequest request, Action<GetLeaderboardResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetFriendLeaderboardRequest, GetLeaderboardResult>("Client", "/Client/GetFriendLeaderboard", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked friends of the current player for the given statistic, centered on the currently signed-in user
        /// </summary>
        public static void GetFriendLeaderboardAroundCurrentUser(GetFriendLeaderboardAroundCurrentUserRequest request, Action<GetFriendLeaderboardAroundCurrentUserResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetFriendLeaderboardAroundCurrentUserRequest, GetFriendLeaderboardAroundCurrentUserResult>("Client", "/Client/GetFriendLeaderboardAroundCurrentUser", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked friends of the current player for the given statistic, centered on the requested PlayFab user. If PlayFabId is empty or null will return currently logged in user.
        /// </summary>
        public static void GetFriendLeaderboardAroundPlayer(GetFriendLeaderboardAroundPlayerRequest request, Action<GetFriendLeaderboardAroundPlayerResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetFriendLeaderboardAroundPlayerRequest, GetFriendLeaderboardAroundPlayerResult>("Client", "/Client/GetFriendLeaderboardAroundPlayer", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked users for the given statistic, starting from the indicated point in the leaderboard
        /// </summary>
        public static void GetLeaderboard(GetLeaderboardRequest request, Action<GetLeaderboardResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetLeaderboardRequest, GetLeaderboardResult>("Client", "/Client/GetLeaderboard", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked users for the given statistic, centered on the currently signed-in user
        /// </summary>
        public static void GetLeaderboardAroundCurrentUser(GetLeaderboardAroundCurrentUserRequest request, Action<GetLeaderboardAroundCurrentUserResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetLeaderboardAroundCurrentUserRequest, GetLeaderboardAroundCurrentUserResult>("Client", "/Client/GetLeaderboardAroundCurrentUser", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked users for the given statistic, centered on the requested player. If PlayFabId is empty or null will return currently logged in user.
        /// </summary>
        public static void GetLeaderboardAroundPlayer(GetLeaderboardAroundPlayerRequest request, Action<GetLeaderboardAroundPlayerResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetLeaderboardAroundPlayerRequest, GetLeaderboardAroundPlayerResult>("Client", "/Client/GetLeaderboardAroundPlayer", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the indicated statistics (current version and values for all statistics, if none are specified), for the local player.
        /// </summary>
        public static void GetPlayerStatistics(GetPlayerStatisticsRequest request, Action<GetPlayerStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayerStatisticsRequest, GetPlayerStatisticsResult>("Client", "/Client/GetPlayerStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the information on the available versions of the specified statistic.
        /// </summary>
        public static void GetPlayerStatisticVersions(GetPlayerStatisticVersionsRequest request, Action<GetPlayerStatisticVersionsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayerStatisticVersionsRequest, GetPlayerStatisticVersionsResult>("Client", "/Client/GetPlayerStatisticVersions", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title-specific custom data for the user which is readable and writable by the client
        /// </summary>
        public static void GetUserData(GetUserDataRequest request, Action<GetUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserDataRequest, GetUserDataResult>("Client", "/Client/GetUserData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the publisher-specific custom data for the user which is readable and writable by the client
        /// </summary>
        public static void GetUserPublisherData(GetUserDataRequest request, Action<GetUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserDataRequest, GetUserDataResult>("Client", "/Client/GetUserPublisherData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the publisher-specific custom data for the user which can only be read by the client
        /// </summary>
        public static void GetUserPublisherReadOnlyData(GetUserDataRequest request, Action<GetUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserDataRequest, GetUserDataResult>("Client", "/Client/GetUserPublisherReadOnlyData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title-specific custom data for the user which can only be read by the client
        /// </summary>
        public static void GetUserReadOnlyData(GetUserDataRequest request, Action<GetUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserDataRequest, GetUserDataResult>("Client", "/Client/GetUserReadOnlyData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the details of all title-specific statistics for the user
        /// </summary>
        public static void GetUserStatistics(GetUserStatisticsRequest request, Action<GetUserStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserStatisticsRequest, GetUserStatisticsResult>("Client", "/Client/GetUserStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Updates the values of the specified title-specific statistics for the user. By default, clients are not permitted to update statistics. Developers may override this setting in the Game Manager > Settings > API Features.
        /// </summary>
        public static void UpdatePlayerStatistics(UpdatePlayerStatisticsRequest request, Action<UpdatePlayerStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdatePlayerStatisticsRequest, UpdatePlayerStatisticsResult>("Client", "/Client/UpdatePlayerStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Creates and updates the title-specific custom data for the user which is readable and writable by the client
        /// </summary>
        public static void UpdateUserData(UpdateUserDataRequest request, Action<UpdateUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateUserDataRequest, UpdateUserDataResult>("Client", "/Client/UpdateUserData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Creates and updates the publisher-specific custom data for the user which is readable and writable by the client
        /// </summary>
        public static void UpdateUserPublisherData(UpdateUserDataRequest request, Action<UpdateUserDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateUserDataRequest, UpdateUserDataResult>("Client", "/Client/UpdateUserPublisherData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Updates the values of the specified title-specific statistics for the user. By default, clients are not permitted to update statistics. Developers may override this setting in the Game Manager > Settings > API Features.
        /// </summary>
        public static void UpdateUserStatistics(UpdateUserStatisticsRequest request, Action<UpdateUserStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateUserStatisticsRequest, UpdateUserStatisticsResult>("Client", "/Client/UpdateUserStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the specified version of the title's catalog of virtual goods, including all defined properties
        /// </summary>
        public static void GetCatalogItems(GetCatalogItemsRequest request, Action<GetCatalogItemsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCatalogItemsRequest, GetCatalogItemsResult>("Client", "/Client/GetCatalogItems", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the key-value store of custom publisher settings
        /// </summary>
        public static void GetPublisherData(GetPublisherDataRequest request, Action<GetPublisherDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPublisherDataRequest, GetPublisherDataResult>("Client", "/Client/GetPublisherData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the set of items defined for the specified store, including all prices defined
        /// </summary>
        public static void GetStoreItems(GetStoreItemsRequest request, Action<GetStoreItemsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetStoreItemsRequest, GetStoreItemsResult>("Client", "/Client/GetStoreItems", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the key-value store of custom title settings
        /// </summary>
        public static void GetTitleData(GetTitleDataRequest request, Action<GetTitleDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetTitleDataRequest, GetTitleDataResult>("Client", "/Client/GetTitleData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title news feed, as configured in the developer portal
        /// </summary>
        public static void GetTitleNews(GetTitleNewsRequest request, Action<GetTitleNewsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetTitleNewsRequest, GetTitleNewsResult>("Client", "/Client/GetTitleNews", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Increments the user's balance of the specified virtual currency by the stated amount
        /// </summary>
        public static void AddUserVirtualCurrency(AddUserVirtualCurrencyRequest request, Action<ModifyUserVirtualCurrencyResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AddUserVirtualCurrencyRequest, ModifyUserVirtualCurrencyResult>("Client", "/Client/AddUserVirtualCurrency", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Confirms with the payment provider that the purchase was approved (if applicable) and adjusts inventory and virtual currency balances as appropriate
        /// </summary>
        public static void ConfirmPurchase(ConfirmPurchaseRequest request, Action<ConfirmPurchaseResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ConfirmPurchaseRequest, ConfirmPurchaseResult>("Client", "/Client/ConfirmPurchase", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Consume uses of a consumable item. When all uses are consumed, it will be removed from the player's inventory.
        /// </summary>
        public static void ConsumeItem(ConsumeItemRequest request, Action<ConsumeItemResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ConsumeItemRequest, ConsumeItemResult>("Client", "/Client/ConsumeItem", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the specified character's current inventory of virtual goods
        /// </summary>
        public static void GetCharacterInventory(GetCharacterInventoryRequest request, Action<GetCharacterInventoryResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCharacterInventoryRequest, GetCharacterInventoryResult>("Client", "/Client/GetCharacterInventory", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a completed purchase along with its current PlayFab status.
        /// </summary>
        public static void GetPurchase(GetPurchaseRequest request, Action<GetPurchaseResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPurchaseRequest, GetPurchaseResult>("Client", "/Client/GetPurchase", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the user's current inventory of virtual goods
        /// </summary>
        public static void GetUserInventory(GetUserInventoryRequest request, Action<GetUserInventoryResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetUserInventoryRequest, GetUserInventoryResult>("Client", "/Client/GetUserInventory", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Selects a payment option for purchase order created via StartPurchase
        /// </summary>
        public static void PayForPurchase(PayForPurchaseRequest request, Action<PayForPurchaseResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<PayForPurchaseRequest, PayForPurchaseResult>("Client", "/Client/PayForPurchase", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Buys a single item with virtual currency. You must specify both the virtual currency to use to purchase, as well as what the client believes the price to be. This lets the server fail the purchase if the price has changed.
        /// </summary>
        public static void PurchaseItem(PurchaseItemRequest request, Action<PurchaseItemResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<PurchaseItemRequest, PurchaseItemResult>("Client", "/Client/PurchaseItem", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Adds the virtual goods associated with the coupon to the user's inventory. Coupons can be generated  via the Promotions->Coupons tab in the PlayFab Game Manager. See this post for more information on coupons:  https://playfab.com/blog/using-stores-and-coupons-game-manager/
        /// </summary>
        public static void RedeemCoupon(RedeemCouponRequest request, Action<RedeemCouponResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RedeemCouponRequest, RedeemCouponResult>("Client", "/Client/RedeemCoupon", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Creates an order for a list of items from the title catalog
        /// </summary>
        public static void StartPurchase(StartPurchaseRequest request, Action<StartPurchaseResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<StartPurchaseRequest, StartPurchaseResult>("Client", "/Client/StartPurchase", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Decrements the user's balance of the specified virtual currency by the stated amount
        /// </summary>
        public static void SubtractUserVirtualCurrency(SubtractUserVirtualCurrencyRequest request, Action<ModifyUserVirtualCurrencyResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<SubtractUserVirtualCurrencyRequest, ModifyUserVirtualCurrencyResult>("Client", "/Client/SubtractUserVirtualCurrency", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Opens the specified container, with the specified key (when required), and returns the contents of the opened container. If the container (and key when relevant) are consumable (RemainingUses > 0), their RemainingUses will be decremented, consistent with the operation of ConsumeItem.
        /// </summary>
        public static void UnlockContainerInstance(UnlockContainerInstanceRequest request, Action<UnlockContainerItemResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlockContainerInstanceRequest, UnlockContainerItemResult>("Client", "/Client/UnlockContainerInstance", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Searches target inventory for an ItemInstance matching the given CatalogItemId, if necessary unlocks it using an appropriate key, and returns the contents of the opened container. If the container (and key when relevant) are consumable (RemainingUses > 0), their RemainingUses will be decremented, consistent with the operation of ConsumeItem.
        /// </summary>
        public static void UnlockContainerItem(UnlockContainerItemRequest request, Action<UnlockContainerItemResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UnlockContainerItemRequest, UnlockContainerItemResult>("Client", "/Client/UnlockContainerItem", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Adds the PlayFab user, based upon a match against a supplied unique identifier, to the friend list of the local user. At least one of FriendPlayFabId,FriendUsername,FriendEmail, or FriendTitleDisplayName should be initialized.
        /// </summary>
        public static void AddFriend(AddFriendRequest request, Action<AddFriendResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AddFriendRequest, AddFriendResult>("Client", "/Client/AddFriend", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the current friend list for the local user, constrained to users who have PlayFab accounts. Friends from linked accounts (Facebook, Steam) are also included. You may optionally exclude some linked services' friends.
        /// </summary>
        public static void GetFriendsList(GetFriendsListRequest request, Action<GetFriendsListResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetFriendsListRequest, GetFriendsListResult>("Client", "/Client/GetFriendsList", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Removes a specified user from the friend list of the local user
        /// </summary>
        public static void RemoveFriend(RemoveFriendRequest request, Action<RemoveFriendResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RemoveFriendRequest, RemoveFriendResult>("Client", "/Client/RemoveFriend", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Updates the tag list for a specified user in the friend list of the local user
        /// </summary>
        public static void SetFriendTags(SetFriendTagsRequest request, Action<SetFriendTagsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<SetFriendTagsRequest, SetFriendTagsResult>("Client", "/Client/SetFriendTags", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Registers the iOS device to receive push notifications
        /// </summary>
        public static void RegisterForIOSPushNotification(RegisterForIOSPushNotificationRequest request, Action<RegisterForIOSPushNotificationResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RegisterForIOSPushNotificationRequest, RegisterForIOSPushNotificationResult>("Client", "/Client/RegisterForIOSPushNotification", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Restores all in-app purchases based on the given refresh receipt.
        /// </summary>
        public static void RestoreIOSPurchases(RestoreIOSPurchasesRequest request, Action<RestoreIOSPurchasesResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RestoreIOSPurchasesRequest, RestoreIOSPurchasesResult>("Client", "/Client/RestoreIOSPurchases", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Validates with the Apple store that the receipt for an iOS in-app purchase is valid and that it matches the purchased catalog item
        /// </summary>
        public static void ValidateIOSReceipt(ValidateIOSReceiptRequest request, Action<ValidateIOSReceiptResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ValidateIOSReceiptRequest, ValidateIOSReceiptResult>("Client", "/Client/ValidateIOSReceipt", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Get details about all current running game servers matching the given parameters.
        /// </summary>
        public static void GetCurrentGames(CurrentGamesRequest request, Action<CurrentGamesResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<CurrentGamesRequest, CurrentGamesResult>("Client", "/Client/GetCurrentGames", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        ///  Get details about the regions hosting game servers matching the given parameters.
        /// </summary>
        public static void GetGameServerRegions(GameServerRegionsRequest request, Action<GameServerRegionsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GameServerRegionsRequest, GameServerRegionsResult>("Client", "/Client/GetGameServerRegions", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Attempts to locate a game session matching the given parameters. If the goal is to match the player into a specific active session, only the LobbyId is required. Otherwise, the BuildVersion, GameMode, and Region are all required parameters. Note that parameters specified in the search are required (they are not weighting factors). If a slot is found in a server instance matching the parameters, the slot will be assigned to that player, removing it from the availabe set. In that case, the information on the game session will be returned, otherwise the Status returned will be GameNotFound. Note that EnableQueue is deprecated at this time.
        /// </summary>
        public static void Matchmake(MatchmakeRequest request, Action<MatchmakeResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<MatchmakeRequest, MatchmakeResult>("Client", "/Client/Matchmake", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Start a new game server with a given configuration, add the current player and return the connection information.
        /// </summary>
        public static void StartGame(StartGameRequest request, Action<StartGameResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<StartGameRequest, StartGameResult>("Client", "/Client/StartGame", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Registers the Android device to receive push notifications
        /// </summary>
        public static void AndroidDevicePushNotificationRegistration(AndroidDevicePushNotificationRegistrationRequest request, Action<AndroidDevicePushNotificationRegistrationResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AndroidDevicePushNotificationRegistrationRequest, AndroidDevicePushNotificationRegistrationResult>("Client", "/Client/AndroidDevicePushNotificationRegistration", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Validates a Google Play purchase and gives the corresponding item to the player.
        /// </summary>
        public static void ValidateGooglePlayPurchase(ValidateGooglePlayPurchaseRequest request, Action<ValidateGooglePlayPurchaseResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ValidateGooglePlayPurchaseRequest, ValidateGooglePlayPurchaseResult>("Client", "/Client/ValidateGooglePlayPurchase", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Logs a custom analytics event
        /// </summary>
        public static void LogEvent(LogEventRequest request, Action<LogEventResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<LogEventRequest, LogEventResult>("Client", "/Client/LogEvent", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Writes a character-based event into PlayStream.
        /// </summary>
        public static void WriteCharacterEvent(WriteClientCharacterEventRequest request, Action<WriteEventResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<WriteClientCharacterEventRequest, WriteEventResponse>("Client", "/Client/WriteCharacterEvent", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Writes a player-based event into PlayStream.
        /// </summary>
        public static void WritePlayerEvent(WriteClientPlayerEventRequest request, Action<WriteEventResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<WriteClientPlayerEventRequest, WriteEventResponse>("Client", "/Client/WritePlayerEvent", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Writes a title-based event into PlayStream.
        /// </summary>
        public static void WriteTitleEvent(WriteTitleEventRequest request, Action<WriteEventResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<WriteTitleEventRequest, WriteEventResponse>("Client", "/Client/WriteTitleEvent", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Adds users to the set of those able to update both the shared data, as well as the set of users in the group. Only users in the group can add new members.
        /// </summary>
        public static void AddSharedGroupMembers(AddSharedGroupMembersRequest request, Action<AddSharedGroupMembersResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AddSharedGroupMembersRequest, AddSharedGroupMembersResult>("Client", "/Client/AddSharedGroupMembers", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Requests the creation of a shared group object, containing key/value pairs which may be updated by all members of the group. Upon creation, the current user will be the only member of the group.
        /// </summary>
        public static void CreateSharedGroup(CreateSharedGroupRequest request, Action<CreateSharedGroupResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<CreateSharedGroupRequest, CreateSharedGroupResult>("Client", "/Client/CreateSharedGroup", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves data stored in a shared group object, as well as the list of members in the group. Non-members of the group may use this to retrieve group data, including membership, but they will not receive data for keys marked as private.
        /// </summary>
        public static void GetSharedGroupData(GetSharedGroupDataRequest request, Action<GetSharedGroupDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetSharedGroupDataRequest, GetSharedGroupDataResult>("Client", "/Client/GetSharedGroupData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Removes users from the set of those able to update the shared data and the set of users in the group. Only users in the group can remove members. If as a result of the call, zero users remain with access, the group and its associated data will be deleted.
        /// </summary>
        public static void RemoveSharedGroupMembers(RemoveSharedGroupMembersRequest request, Action<RemoveSharedGroupMembersResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RemoveSharedGroupMembersRequest, RemoveSharedGroupMembersResult>("Client", "/Client/RemoveSharedGroupMembers", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Adds, updates, and removes data keys for a shared group object. If the permission is set to Public, all fields updated or added in this call will be readable by users not in the group. By default, data permissions are set to Private. Regardless of the permission setting, only members of the group can update the data.
        /// </summary>
        public static void UpdateSharedGroupData(UpdateSharedGroupDataRequest request, Action<UpdateSharedGroupDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateSharedGroupDataRequest, UpdateSharedGroupDataResult>("Client", "/Client/UpdateSharedGroupData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Executes a CloudScript function, with the 'currentPlayerId' set to the PlayFab ID of the authenticated player.
        /// </summary>
        public static void ExecuteCloudScript(ExecuteCloudScriptRequest request, Action<ExecuteCloudScriptResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ExecuteCloudScriptRequest, ExecuteCloudScriptResult>("Client", "/Client/ExecuteCloudScript", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title-specific URL for Cloud Script servers. This must be queried once, prior  to making any calls to RunCloudScript.
        /// </summary>
        public static void GetCloudScriptUrl(GetCloudScriptUrlRequest request, Action<GetCloudScriptUrlResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCloudScriptUrlRequest, GetCloudScriptUrlResult>("Client", "/Client/GetCloudScriptUrl", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Triggers a particular server action, passing the provided inputs to the hosted Cloud Script. An action in this context is a handler in the JavaScript. NOTE: Before calling this API, you must call GetCloudScriptUrl to be assigned a Cloud Script server URL. When using an official PlayFab SDK, this URL is stored internally in the SDK, but GetCloudScriptUrl must still be manually called.
        /// </summary>
        public static void RunCloudScript(RunCloudScriptRequest request, Action<RunCloudScriptResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<RunCloudScriptRequest, RunCloudScriptResult>("Client", "/Client/RunCloudScript", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// This API retrieves a pre-signed URL for accessing a content file for the title. A subsequent  HTTP GET to the returned URL will attempt to download the content. A HEAD query to the returned URL will attempt to  retrieve the metadata of the content. Note that a successful result does not guarantee the existence of this content -  if it has not been uploaded, the query to retrieve the data will fail. See this post for more information:  https://community.playfab.com/hc/en-us/community/posts/205469488-How-to-upload-files-to-PlayFab-s-Content-Service
        /// </summary>
        public static void GetContentDownloadUrl(GetContentDownloadUrlRequest request, Action<GetContentDownloadUrlResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetContentDownloadUrlRequest, GetContentDownloadUrlResult>("Client", "/Client/GetContentDownloadUrl", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Lists all of the characters that belong to a specific user. CharacterIds are not globally unique; characterId must be evaluated with the parent PlayFabId to guarantee uniqueness.
        /// </summary>
        public static void GetAllUsersCharacters(ListUsersCharactersRequest request, Action<ListUsersCharactersResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ListUsersCharactersRequest, ListUsersCharactersResult>("Client", "/Client/GetAllUsersCharacters", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked characters for the given statistic, starting from the indicated point in the leaderboard
        /// </summary>
        public static void GetCharacterLeaderboard(GetCharacterLeaderboardRequest request, Action<GetCharacterLeaderboardResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCharacterLeaderboardRequest, GetCharacterLeaderboardResult>("Client", "/Client/GetCharacterLeaderboard", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the details of all title-specific statistics for the user
        /// </summary>
        public static void GetCharacterStatistics(GetCharacterStatisticsRequest request, Action<GetCharacterStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCharacterStatisticsRequest, GetCharacterStatisticsResult>("Client", "/Client/GetCharacterStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of ranked characters for the given statistic, centered on the requested Character ID
        /// </summary>
        public static void GetLeaderboardAroundCharacter(GetLeaderboardAroundCharacterRequest request, Action<GetLeaderboardAroundCharacterResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetLeaderboardAroundCharacterRequest, GetLeaderboardAroundCharacterResult>("Client", "/Client/GetLeaderboardAroundCharacter", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves a list of all of the user's characters for the given statistic.
        /// </summary>
        public static void GetLeaderboardForUserCharacters(GetLeaderboardForUsersCharactersRequest request, Action<GetLeaderboardForUsersCharactersResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetLeaderboardForUsersCharactersRequest, GetLeaderboardForUsersCharactersResult>("Client", "/Client/GetLeaderboardForUserCharacters", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Grants the specified character type to the user. CharacterIds are not globally unique; characterId must be evaluated with the parent PlayFabId to guarantee uniqueness.
        /// </summary>
        public static void GrantCharacterToUser(GrantCharacterToUserRequest request, Action<GrantCharacterToUserResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GrantCharacterToUserRequest, GrantCharacterToUserResult>("Client", "/Client/GrantCharacterToUser", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Updates the values of the specified title-specific statistics for the specific character. By default, clients are not permitted to update statistics. Developers may override this setting in the Game Manager > Settings > API Features.
        /// </summary>
        public static void UpdateCharacterStatistics(UpdateCharacterStatisticsRequest request, Action<UpdateCharacterStatisticsResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateCharacterStatisticsRequest, UpdateCharacterStatisticsResult>("Client", "/Client/UpdateCharacterStatistics", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title-specific custom data for the character which is readable and writable by the client
        /// </summary>
        public static void GetCharacterData(GetCharacterDataRequest request, Action<GetCharacterDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCharacterDataRequest, GetCharacterDataResult>("Client", "/Client/GetCharacterData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Retrieves the title-specific custom data for the character which can only be read by the client
        /// </summary>
        public static void GetCharacterReadOnlyData(GetCharacterDataRequest request, Action<GetCharacterDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetCharacterDataRequest, GetCharacterDataResult>("Client", "/Client/GetCharacterReadOnlyData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Creates and updates the title-specific custom data for the user's character which is readable  and writable by the client
        /// </summary>
        public static void UpdateCharacterData(UpdateCharacterDataRequest request, Action<UpdateCharacterDataResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<UpdateCharacterDataRequest, UpdateCharacterDataResult>("Client", "/Client/UpdateCharacterData", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Validates with Amazon that the receipt for an Amazon App Store in-app purchase is valid and that it matches the purchased catalog item
        /// </summary>
        public static void ValidateAmazonIAPReceipt(ValidateAmazonReceiptRequest request, Action<ValidateAmazonReceiptResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<ValidateAmazonReceiptRequest, ValidateAmazonReceiptResult>("Client", "/Client/ValidateAmazonIAPReceipt", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Accepts an open trade. If the call is successful, the offered and accepted items will be swapped between the two players' inventories.
        /// </summary>
        public static void AcceptTrade(AcceptTradeRequest request, Action<AcceptTradeResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AcceptTradeRequest, AcceptTradeResponse>("Client", "/Client/AcceptTrade", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Cancels an open trade.
        /// </summary>
        public static void CancelTrade(CancelTradeRequest request, Action<CancelTradeResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<CancelTradeRequest, CancelTradeResponse>("Client", "/Client/CancelTrade", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Gets all trades the player has either opened or accepted, optionally filtered by trade status.
        /// </summary>
        public static void GetPlayerTrades(GetPlayerTradesRequest request, Action<GetPlayerTradesResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetPlayerTradesRequest, GetPlayerTradesResponse>("Client", "/Client/GetPlayerTrades", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Gets the current status of an existing trade.
        /// </summary>
        public static void GetTradeStatus(GetTradeStatusRequest request, Action<GetTradeStatusResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<GetTradeStatusRequest, GetTradeStatusResponse>("Client", "/Client/GetTradeStatus", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Opens a new outstanding trade.
        /// </summary>
        public static void OpenTrade(OpenTradeRequest request, Action<OpenTradeResponse> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<OpenTradeRequest, OpenTradeResponse>("Client", "/Client/OpenTrade", request , "X-Authorization", resultCallback, errorCallback, customData);
        }

        /// <summary>
        /// Attributes an install for advertisment.
        /// </summary>
        public static void AttributeInstall(AttributeInstallRequest request, Action<AttributeInstallResult> resultCallback, Action<PlayFabError> errorCallback, object customData = null)
        {
            if (!IsClientLoggedIn()) throw new Exception("Must be logged in to call this method");

            PlayFabHttp.MakeApiCall<AttributeInstallRequest, AttributeInstallResult>("Client", "/Client/AttributeInstall", request , "X-Authorization", resultCallback, errorCallback, customData);
        }


    }
}
#endif
